services:
  - type: web
    name: ethicali-streamlit
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PRIVATE_KEY
        sync: false
      - key: METAMASK_ACCOUNT_ADDRESS
        sync: false
      - key: SEPOLIA_RPC_URL
        sync: false
      - key: ETHICALI_DDB_TABLE
        value: EthicaliAuditLogs
      - key: AWS_REGION
        value: us-east-1
